# Generated by Django 5.1.5 on 2025-02-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='This is a placeholder description.'),
        ),
    ]
