# Generated by Django 5.1.5 on 2025-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
