# Generated by Django 5.1.5 on 2025-02-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
